import type { Fn } from '../fns'

export const adapters: Fn[] = [
  // Filter
  {
    name: 'filter',
    args: ['predicate'],
    category: ['Adapters', 'Filter'],
    description: 'Creates an iterator which uses a closure to determine if an element should be yielded.',
    related: ['filter_map'],
  },
  {
    name: 'step_by',
    args: ['step'],
    category: ['Adapters', 'Filter'],
    description: 'Creates an iterator starting at the same point, but stepping by the given amount at each iteration.',
  },
  {
    name: 'skip',
    args: ['n'],
    category: ['Adapters', 'Filter'],
    description: 'Creates an iterator that skips the first <code>n</code> elements.',
  },
  {
    name: 'skip_while',
    args: ['predicate'],
    category: ['Adapters', 'Filter'],
    description: 'Creates an iterator that skips elements based on a predicate.',
  },
  {
    name: 'take',
    args: ['n'],
    category: ['Adapters', 'Filter'],
    description:
      'Creates an iterator that yields the first <code>n</code> elements, or fewer if the underlying iterator ends sooner.',
  },
  {
    name: 'take_while',
    args: ['predicate'],
    category: ['Adapters', 'Filter'],
    description: 'Creates an iterator that yields elements while the given predicate returns <code>true</code>.',
  },
  {
    name: 'fuse',
    args: [],
    category: ['Adapters', 'Filter'],
    description: 'Creates an iterator which ends after the first <code>None</code>.',
  },
  // Expand
  {
    name: 'chain',
    args: ['iterator'],
    category: ['Adapters', 'Expand'],
    description: 'Takes two iterators and creates a new iterator over both in sequence.',
  },
  {
    name: 'cycle',
    args: [],
    category: ['Adapters', 'Expand'],
    description: 'Repeats an iterator endlessly.',
  },
  {
    name: 'intersperse',
    args: ['separator'],
    category: ['Adapters', 'Expand'],
    description:
      'Creates a new iterator which places a copy of <code>separator</code> between adjacent items of the original iterator.',
    nightly: true,
  },
  {
    name: 'intersperse_with',
    args: ['separator_fn'],
    category: ['Adapters', 'Expand'],
    description:
      'Creates a new iterator which places an item generated by <code>separator_fn</code> between adjacent items of the original iterator.',
    nightly: true,
  },
  // Transform
  {
    name: 'enumerate',
    args: [],
    category: ['Adapters', 'Transform'],
    description: 'Creates an iterator which gives the current iteration count as well as the next value.',
  },
  {
    name: 'map',
    args: ['transform'],
    category: ['Adapters', 'Transform'],
    description: 'Takes a closure and creates an iterator which calls that closure on each element.',
  },
  {
    name: 'zip',
    args: ['iterable'],
    category: ['Adapters', 'Transform'],
    description: '‘Zips up’ two iterators into a single iterator of pairs.',
    related: ['unzip'],
  },
  {
    name: 'flatten',
    args: [],
    category: ['Adapters', 'Transform'],
    description: 'Creates an iterator that flattens nested structure.',
    related: ['flat_map'],
  },
  {
    name: 'copied',
    args: [],
    category: ['Adapters', 'Transform'],
    description: 'Creates an iterator which copies all of its elements.',
  },
  {
    name: 'cloned',
    args: [],
    category: ['Adapters', 'Transform'],
    description: 'Creates an iterator which <code>clone</code>s all of its elements.',
  },
  {
    name: 'flat_map',
    args: ['transform'],
    category: ['Adapters', 'Transform'],
    description: 'Creates an iterator that works like map, but flattens nested structure.',
    related: ['map'],
  },
  {
    name: 'filter_map',
    args: ['transform'],
    category: ['Adapters', 'Transform'],
    description: 'Creates an iterator that both filters and maps.',
    related: ['filter'],
  },
  {
    name: 'map_while',
    args: ['transform'],
    category: ['Adapters', 'Transform'],
    description: 'Creates an iterator that both yields elements based on a predicate and maps.',
    related: ['take_while'],
  },
  {
    name: 'scan',
    args: ['init', 'accumulate'],
    category: ['Adapters', 'Transform'],
    description:
      'An iterator adapter which, like <code>fold</code>, holds internal state, but unlike <code>fold</code>, produces a new iterator.',
    related: ['fold'],
  },
  {
    name: 'array_chunks',
    args: [],
    generic_args: ['const N'],
    category: ['Adapters', 'Transform'],
    description: 'Returns an iterator over <code>N</code> elements of the iterator at a time.',
    nightly: true,
  },
  {
    name: 'map_windows',
    args: ['transform'],
    generic_args: ['const N'],
    category: ['Adapters', 'Transform'],
    description:
      'Calls the given function for each contiguous window of size <code>N</code> over <code>self</code> and returns an iterator over the outputs.',
    related: ['windows'],
    nightly: true,
  },
  // Misc.
  {
    name: 'inspect',
    args: ['function'],
    category: ['Adapters', 'Misc.'],
    description: 'Does something with each element of an iterator, passing the value on.',
  },
  {
    name: 'peekable',
    args: [],
    category: ['Adapters', 'Misc.'],
    description:
      'Creates an iterator which can use the <code>peek</code> and <code>peek_mut</code> methods to look at the next element of the iterator without consuming it.',
  },
  {
    name: 'rev',
    args: [],
    category: ['Adapters', 'Misc.'],
    description: 'Reverses an iterator’s direction.',
    related: ['last', 'rposition'],
  },
]
